models/Article.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "article".
 *
 * @property integer $article_id
 * @property integer $sort
 * @property integer $public
 * @property string $public_at
 *
 * @property Content $content
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort', 'public'], 'integer'],
            [['public_at'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'article_id' => 'ID статьи',
            'sort' => 'Порядок',
            'public' => 'Видна всем',
            'title' => 'Заголовок',
            'public_at' => 'Опубликовано',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContent()
    {
        return $this->hasOne(Content::className(), ['article_id' => 'article_id']);
    }
    
    public function afterFind()
    {
        parent::afterFind();
        
        //foreach (['content_id', 'title', 'content'] as $atr) {
        //    $this->{$atr} = $this->contentRecord->{$atr};
        //}
    }
}

models/Content.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "content".
 *
 * @property integer $content_id
 * @property integer $article_id
 * @property string $title
 * @property string $content
 *
 * @property Article $article
 */
class Content extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'content';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['article_id'], 'required'],
            [['article_id'], 'integer'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['article_id'], 'unique'],
            [['article_id'], 'exist', 'skipOnError' => true, 'targetClass' => Article::className(), 'targetAttribute' => ['article_id' => 'article_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'content_id' => 'ID Содержания',
            'article_id' => 'ID Статьи',
            'title' => 'Заголовок',
            'content' => 'Содержание',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['article_id' => 'article_id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\Article;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchForm = new \app\models\forms\ArticleSearchForm();
        
        $searchForm->load(\Yii::$app->request->get());
        //var_dump($searchForm->attributes); exit;
        
        return $this->render('index', ['searchForm' => $searchForm]);
    }
    
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionViewArticle($article_id)
    {
        $model = Article::findOne(['article_id' => $article_id]);
        
        //var_dump($model); exit;
        
        return $this->render('view-article', ['model' => $model]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Тестовый пример',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Тестовый пример <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchForm app\models\forms\ArticleSearchForm */

use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Блог';
?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-lg-12">
                <h2>Статьи</h2>

                <?= GridView::widget([
                    'dataProvider' => $searchForm->search(),
                    'filterModel' => $searchForm,
                    'columns' => [
                        'article_id',
                        'sort',
                        'public_at',
                        [
                            'attribute' => 'title',
                            'content' => function ($model) {
                                return Html::a($model->content->title, Url::to(['site/view-article', 'article_id' => $model->article_id]));
                            }
                        ],
                    ],
                ]); ?>
            </div>
        </div>

    </div>
</div>

views/site/view-article.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Просмотр статьи';
?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-lg-12">
                <h2><?= Html::encode($model->content->title); ?></h2>

                <p><?= Html::encode($model->content->content); ?></p>
                
                <p><?= Html::a('Назад', Url::to(['site/index']), ['class' => 'btn btn-default']); ?></p>
            </div>
        </div>

    </div>
</div>